language: node_js

node_js:
    - '8'

cache:
  directories:
    - node_modules

before_install:
    - "npm install -g npm"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master
